### ISSUE TITLE
如何实现动态加载answer的comment？

### ISSUE THREAD

**Issue by ypling** [CCCBTICC/iOS#1]
看知乎时候 有个回答3000+的评论 全部加载完速度超慢。 ios里能实现下拉到一定位置再发送request吗？
@Zacharysp @apple80024

**Comment by Zacharysp** [comment]
可以实现

**Comment by ypling** [comment]
好的 那我的api就做成按照answer id加载comment了 用于分步加载

**Comment by Zacharysp** [comment]
就有个page number, 一页有固定数目的item, 发request的时候是发page number

**Comment by ypling** [comment]
能不能做到在下拉到某一条answer的时候再去发送answer id加载comment？ @lhz213 说网页这边可以这样做 他研究一下

**Comment by Zacharysp** [comment]
也可以做到，没问题的

**Comment by ypling** [comment]
已经解决了？

**Comment by apple80024** [comment]
good good der !!

**Comment by Zacharysp** [comment]
@ypling 只是关了。。。还没做到那。。。
你又不来。。

**Comment by ypling** [comment]
这两天改简历呢 咱们可以在https://gitter.im/CCCBTICC 聊天
